ckanext/spc/views/package.py
import datetime
import logging
import enum
import io
import os
import urllib
import uuid
import magic
import requests
import json

import funcy as F
from werkzeug.datastructures import FileStorage
from flask import Blueprint, jsonify
from ckan.plugins import toolkit as tk
from ckan.common import g, request, streaming_response, config
import ckan.logic as logic
import ckan.model as model
import ckan.lib.jobs as jobs

from ckanext.spc.utils.xlsx import Exporter, Importer


spc_package = Blueprint("spc_package", __name__)
log = logging.getLogger(__name__)


class ImportState(enum.Enum):
    FAIL = "failed"
    SKIP = "skipped"
    CREATE = "created"
    UPDATE = "updated"


def _get_search_args():
    ignore = {"page", "sort", "q"}
    extras = {}
    fq = ""
    for k, v in request.args.items(multi=True):
        if k in ignore:
            continue
        if k.startswith("ext_"):
            extras[k] = v
        else:
            fq += ' %s:"%s"' % (k, v)
    context = {
        "model": model,
        "session": model.Session,
        "user": g.user,
        "for_view": True,
        "auth_user_obj": g.userobj,
    }
    data_dict = {
        "q": request.args.get("q", "*:*"),
        "fq": fq.strip(),
        "extras": extras,
        "include_private": True,
    }

    return context, data_dict


def list_ids():
    context, data_dict = _get_search_args()
    data_dict["fl"] = "id"
    data_dict["rows"] = 1000
    query = tk.get_action("package_search")(context, data_dict)
    ids = [r["id"] for r in query["results"]]
    return jsonify(ids)


def _exhaustive_search(context, data_dict):
    count = 1000
    offset = 0
    data_dict["rows"] = 100
    while offset < count:
        data_dict["start"] = offset
        query = tk.get_action("package_search")(context, data_dict)
        for pkg in query["results"]:
            yield pkg
        offset += len(query["results"])
        count = query["count"]


def export_datasets(id):
    context, data_dict = _get_search_args()
    data_dict["fq"] += f' owner_org:"{id}"'
    try:
        tk.check_access("spc_export_datasets", context, {"id": id})
    except tk.NotAuthorized:
        return tk.abort(403, tk._("Not authorized to export datasets"))

    exporter = Exporter(_exhaustive_search(context, data_dict))
    resp = streaming_response(exporter.get_stream(), with_context=True)
    resp.headers[
        "content-disposition"
    ] = 'attachment; filename="data_export.xlsx"'
    resp.headers["Last-Modified"] = datetime.datetime.now()
    resp.headers[
        "Cache-Control"
    ] = "no-store, no-cache, must-revalidate, post-check=0, pre-check=0, max-age=0"
    resp.headers["Pragma"] = "no-cache"
    resp.headers["Expires"] = "-1"
    return resp


def _import_dataset(context, dataset, action="package_update"):
    try:
        if dataset.get('spatial', None):
            dataset['spatial'] = json.dumps(dataset['spatial'])
        pkg = tk.get_action(action)(context, dataset)
        if action == "package_update":
            return ImportState.UPDATE, pkg
        return ImportState.CREATE, pkg
    except tk.ValidationError as e:
        msg = f'Validation error during {dataset.get("id")} import: {e}'
        log.error(msg)
        return ImportState.FAIL, {"error": e, "dataset": dataset}


def _handle_imported_dataset(context, dataset):
    dataset = F.select_values(F.notnone, dataset)
    try:
        pkg = tk.get_action("package_show")(context.copy(), dataset)
    except (tk.ObjectNotFound, tk.ValidationError):
        return _import_dataset(context.copy(), dataset, "package_create")

    old_fields = F.project(pkg, dataset)
    new_fields = F.omit(dataset, old_fields)
    for field in new_fields:
        if dataset[field] is None:
            del dataset[field]

    if any(new_fields.values()):
        return _import_dataset(context.copy(), dataset)
    new_fields = F.project(dataset, old_fields)

    new_resources = dataset.setdefault('resources', [])
    old_resources = pkg.setdefault('resources', [])
    for idx, (new, old) in enumerate(zip(new_resources, old_resources)):
        old_resources[idx] = F.project(old, new)
        diff = F.omit(new, old)
        if not any(diff.values()):
            new_resources[idx] = F.omit(new, diff)
    if new_fields == old_fields:
        return ImportState.SKIP, dataset
    return _import_dataset(context.copy(), dataset)


def _get_format(c_type):
    if c_type:
        ct = c_type.split(';')[0]
        ft = ct.split('/')[-1]
        return {'content_type': ct, 'format': ft}
    return {}


def _get_action(upload, extra):
    action = None
    extra_dict = {}
    frm = _get_format(extra.get('content-type', None))
    if upload.get('id', None):
        action = 'resource_update'
        for key, _ in upload.items():
            if key == 'format':
                upload[key] = frm.get('format', '')
            if key == 'mimetype':
                upload[key] = frm.get('content_type', '')
        extra_dict = upload
    else:
        action = 'resource_create'
        extra_dict = {key: value for (key, value) in upload.items() if key not in (
                     'id', 'url', 'format', 'mimetype', 'modified', 'download_location')}
    return action, extra_dict


def _upload_resources(context, resources):

    context.update({"model": model})
    total_uploaded = 0
    for upload in resources:
        package_id = upload['package_id']
        pkg = model.Package.get(package_id)
        if not pkg:
            log.error(f"* Was trying to upload a resource to a dataset which doesn't exist (id: {package_id}). Skipping.")
            continue
        resource_location = upload['download_location'].strip()
        log.info(f"* Uploading {resource_location} to {pkg.name}")
        filename = os.path.basename(resource_location)
        local_file = os.path.isfile(resource_location)
        stream, extra = None, None
        if local_file:
            with open(resource_location, 'rb') as f:
                data = f.read()
                stream = io.BytesIO(data)
                mime = magic.Magic(mime=True)
                extra = {'content-type': mime.from_file(resource_location)}
        else:
            try:
                req = requests.get(resource_location, stream=True)
                extra = req.headers
                dct = dict(extra)
                dct['content-type'] = dct['Content-Type']
                dct.pop('Content-Type')
            except:
                log.error(f"Invalid location provided: {resource_location}. Skipping.")
                continue
            stream = io.BytesIO(req.content)
                
        data_dict = dict(upload=FileStorage(stream, filename, name='file'))
        action, extra_dict = _get_action(upload, extra)
        data_dict.update(extra_dict)

        try:
            m = {'resource_create': 'created', 'resource_update': 'updated'}
            message = f"Resource {resource_location} was successfuly {m[action]} on {pkg.name}"
            cnt_type = extra.get('content-type', None)
            mime_type = upload.get('mimetype', None)
            mimetype = cnt_type if not mime_type else mime_type
            data_dict['mimetype'] = mimetype
            fmt = upload.get('format', None)
            if not fmt:
                try:
                    fmt = mimetype.split('/')[1].upper()
                    data_dict['format'] = fmt
                except:
                    pass
            else:
                data_dict['format'] = fmt
            logic.get_action(action)(context, data_dict)
            log.info(message)
            total_uploaded += 1
        except Exception as e:
            log.error(e)
            continue
    log.info(f"Total uploaded {total_uploaded} of {len(resources)}.")


def import_datasets(id):
    context = {
        "model": model,
        "user": g.user,
    }
    try:
        tk.check_access("spc_import_datasets", context.copy(), {"id": id})
    except tk.NotAuthorized:
        return tk.abort(403, tk._("Not authorized to import datasets"))
    org = model.Group.get(id)
    if not org:
        return tk.abort(404, tk._("Organization not found"))
    snapshot = tk.request.files.get("snapshot")
    if snapshot is None:
        return tk.abort(409, tk._("Data snapshot must be provided"))
    importer = Importer(snapshot)

    datasets = importer.get_datasets()

    results = F.group_by(
        F.first,
        [
            _handle_imported_dataset(context.copy(), dataset)
            for dataset in datasets
        ],
    )

    status_msg = "Import finished: " + ", ".join(
        [f"{state.value}: {len(results[state])}" for state in ImportState]
    )
    tk.h.flash_notice(status_msg)
    res_to_upload = len(importer.resources_to_upload)
    if res_to_upload:
        jobs.enqueue(_upload_resources, kwargs={
            'context': { "user": g.user },
            'resources': importer.resources_to_upload},
            queue='default'
        )
        tk.h.flash_notice(f"Uploading {res_to_upload} resources. This can take some time. Please check default worker log file for details.")
    failed = results[ImportState.FAIL]
    if failed:
        fail_msg = '<br/>'.join([
            f"{fail['dataset'].get('name', 'Unnamed')}: {fail['error'].error_summary}"
            for fail in map(F.second, failed)
        ])
        tk.h.flash_error(fail_msg, True)
    return tk.redirect_to("organization.read", id=org.name)


spc_package.add_url_rule("/dataset/ids/list", view_func=list_ids)
spc_package.add_url_rule(
    "/organization/<id>/export/datasets", view_func=export_datasets
)
spc_package.add_url_rule(
    "/organization/<id>/import/datasets",
    view_func=import_datasets,
    methods=("POST",),
)

ckanext/spc/templates/package/choose_type.html
{% extends "package/base_form_page.html" %}

{% block subtitle %}{{ _('Dataset Type') }}{% endblock %}


{% block breadcrumb_content %}
    <li>{% link_for _('Datasets'), named_route='dataset.search' %}</li>
    <li class="active"><a href="">{{ _('Dataset Type') }}</a></li>
{% endblock %}

ckanext/spc/templates/package/read.html
{% ckan_extends %}

{% block package_description %}
    {% if pkg.private %}
      <span class="dataset-private label label-inverse pull-right">
        <i class="fa fa-lock"></i>
        {{ _('Private') }}
      </span>
    {% endif %}
    {% block package_archive_notice %}
    	{{ super() }}
    {% endblock %}
    <h1>
      {% block page_heading %}
      	{{ super() }}
      {% endblock %}
    </h1>

    <div class="dataset-info">
        Date created: {{ h.render_datetime(pkg.metadata_created, date_format='%d %B %Y') }}
        <div class="data-quality-tooltip">
            <i class="fa fa-question-circle"></i>
            <span class="tooltiptext tooltiptext-above data-quality-tooltip-inner">
                This date indicates the date the dataset metadata was created on Pacific Data Hub.
            </span>
        </div>

    </div>


    {% block package_notes %}
    	{{ super() }}
    {% endblock %}
    {# FIXME why is this here? seems wrong #}
    <span class="insert-comment-thread"></span>



    <div class="dropdown btn-group meta-export-select">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	    <i class="fa spc-icon-external-link meta-export-icon"></i>
	    Export metadata
	    <span class="fa spc-icon-chevron-down-blue meta-export-dropdown-arrow"></span>
	</a>
	<ul class="dropdown-menu">
	    <li>
		<a href="{{ h.url_for('/api/3/action/package_show', id=pkg.id) }}" title="Export metadata as JSON" target="_blank">JSON</a>
	    </li>
	    {% if pkg.type in ['dataset', 'publications', 'biodiversity_data'] %}
		{% set format = {'publications': 'dc-rdf', 'dataset': 'dcat-rdf', 'biodiversity_data': 'eml-rdf'}[pkg.type] %}
		<li>
		    <a
			href="{{ h.url_for('metaexport.export', id=pkg.id, format=format) }}"
			      target="_blank">RDF/XML</a>

		</li>
	    {% endif %}
	    {% if pkg.type in ['biodiversity_data'] %}
		<li>
		    <a
			href="{{ h.url_for('metaexport.export', id=pkg.id, format='eml-xml') }}"
			      target="_blank">EML/XML </a>
		</li>
	    {% endif %}
	    {% if pkg.type in ['geographic_data'] %}
		<li>
		    <a
			href="{{ h.url_for('metaexport.export', id=pkg.id, format='anzlic-xml') }}"
			      target="_blank">XML</a>
		</li>
	    {% endif %}

	</ul>
    </div>

    <div class="pull-right bulk-resource-download-controll hidden-xs hidden-sm">
        {#
        <button class="btn btn-bulk-download " data-module="spc-resource-download-picker" >
        {{ _('Download choosen data') }}
        <span class="picked-counter" data-count="0"></span>
        </button>
        #}
        {% if not h.spc_is_restricted(pkg) or h.check_access('restrict_dataset_show', data_dict=pkg) %}
            <button class="btn btn-bulk-download btn-bulk-download-dark"
                    data-module="spc-bulk-download"
                    data-module-query-string="{{ h.url_for('spc_package.list_ids') }}?q=id:{{ pkg.id }}"
            >
            {{ _('Download all') }}
            {% set pkg_size = h.spc_get_package_size(pkg) %}
            {% if pkg_size != '0 B' %} ({{ pkg_size }}) {% endif %}
            <i class="spc-icon spc-icon-zip-folder"></i>
            </button>
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
     var package = {{ pkg|tojson }}
    </script>
{% endblock scripts %}

ckanext/spc/templates/package/read_base.html
{% extends "package/base.html" %}

{% set pkg = c.pkg_dict or pkg_dict %}

{% block breadcrumb_content_selected %} class="active"{% endblock %}

{% block subtitle %}{{ h.dataset_display_name(pkg) }} - {{ super() }}{% endblock %}

{%- block content %}
  {% block maintag %}<div role="main">{% endblock %}
    <div id="content" class="container">
      {% block main_content %}
        {% block flash %}
          <div class="flash-messages">
            {% block flash_inner %}
              {% for message in h.flash.pop_messages() | list %}
                <div class="alert fade in {{ message.category }}">
                  {{ h.literal(message) }}
                </div>
              {% endfor %}
            {% endblock %}
          </div>
        {% endblock %}

        {% block toolbar %}
          <div class="toolbar">
            {% block breadcrumb %}
              {% if self.breadcrumb_content() | trim %}
                <ol class="breadcrumb">
                  {% snippet 'snippets/home_breadcrumb_item.html' %}
                  {% block breadcrumb_content %}
                    {% if pkg %}
                      {% set dataset = h.dataset_display_name(pkg) %}
                      {% if pkg.organization %}
                        {% set organization = h.get_translated(pkg.organization, 'title') or pkg.organization.name %}
                        <li>{% link_for _('Organizations'), named_route='organization.index' %}</li>
                        <li>{% link_for organization|truncate(30), named_route='organization.read', id=pkg.organization.name %}</li>
                      {% else %}
                        <li>{% link_for _('Datasets'), named_route='dataset.search' %}</li>
                      {% endif %}
                    {% else %}
                      <li>{% link_for _('Datasets'), named_route='dataset.search' %}</li>
                      <li class="active"><a href="">{{ _('Create Dataset') }}</a></li>
                    {% endif %}
                  {% endblock %}
                </ol>
              {% endif %}
            {% endblock %}
          </div>
        {% endblock %}

        <div class="dataset-read row wrapper{% block wrapper_class %}{% endblock %}{% if self.secondary()|trim == '' %} no-nav{% endif %}">
          {% block primary %}
            <div class="primary span9">
                <ul class="nav nav-tabs">
                    {% block content_primary_nav %}
                        {{ h.build_nav_icon('dataset.read', _('Dataset'), id=pkg.name) }}
                        {{ h.build_nav_icon('dataset.groups', _('Groups'), id=pkg.name) }}
                        {{ h.build_nav_icon('dataset.activity', _('Activity Stream'), id=pkg.name) }}
                        {% if h.spc_is_restricted(pkg) and h.check_access('manage_access_requests', data_dict=pkg) %}
                            {{ h.build_nav_icon('spc_access_request.pkg_requests', _('Approved Requests'), pkg_id=pkg.id, icon='clock-o') }}
                        {% endif %}
                        {% if h.spc_is_restricted(pkg) and h.check_access('spc_download_tracking_list', pkg) %}
                            {{ h.build_nav_icon('spc_access_request.package_download_tracking', _('Downloads'), id=pkg.name, package_type=pkg.type, icon='download') }}
                        {% endif %}

                    {% endblock %}
              </ul>
              {% block primary_content %}
                <article class="module">
                  {% block page_header %}
                  {% endblock %}
                  <div class="module-content">
                    {% if self.page_primary_action() | trim %}
                      <div class="page_primary_action">
                        {% block page_primary_action %}{% endblock %}
                      </div>
                    {% endif %}
                    {% block primary_content_inner %}
                      {% block package_revision_info %}
                        {% if h.check_access('package_update', {'id':pkg.id }) %}
                          {% link_for _('Manage'), named_route='dataset.edit', id=pkg.name, class_='btn btn-primary manage', icon='wrench' %}
                        {% endif %}
                        {% if c.revision_date %}
                          <div class="module info alert alert-info">
                            <p class="module-content">
                              {% set timestamp = h.render_datetime(c.revision_date, with_hours=True) %}
                              {% set url = h.url_for('dataset.read', id=pkg.name) %}
                              {% trans timestamp=timestamp, url=url %}This is an old revision of this dataset, as edited at {{ timestamp }}. It may differ significantly from the <a href="{{ url }}">current revision</a>.{% endtrans %}
                            </p>
                          </div>
                        {% endif %}
                      {% endblock %}
                  {% endblock %}
                  </div>
                </article>
              {% endblock %}
            </div>
          {% endblock %}

          {% block secondary %}
            <aside class="secondary span3">
              {% block secondary_content %}

                {% block secondary_help_content %}{% endblock %}

                {% snippet 'package/snippets/rating-stars.html', rating=pkg.get('five_star_rating', 0), dataset_page=true %}

                {% block package_info %}
                  {% snippet 'package/snippets/info.html', pkg=pkg %}
                {% endblock %}

                {% block package_organization %}
                  {% if pkg.organization %}
                    {% set org = h.get_organization(pkg.organization.name) %}
                    {% snippet "snippets/organization.html", organization=org, has_context_title=true %}
                  {% endif %}
                {% endblock %}

                {% block package_social %}
                  {% snippet "snippets/social.html" %}
                {% endblock %}

                {% block package_license %}
                  {% snippet "snippets/license.html", pkg_dict=pkg %}
                {% endblock %}

              {% endblock %}
            </aside>
          {% endblock %}

        </div>
      {% endblock %}
    </div>
  </div>
{% endblock -%}

{% block footer %}
  {% include 'access/snippets/request_access_modal.html' %}
{% endblock %}

ckanext/spc/templates/package/resources.html
{% ckan_extends %}

{% block primary_content_inner %}
    {% if pkg.resources %}
        <ul class="resource-list"{% if has_reorder %} data-module="resource-reorder" data-module-id="{{ pkg.id }}"{% endif %}>

            {% for resource in pkg.resources %}
                {% set can_edit = h.check_access('resource_update', {'id':resource.id }) %}
                {% snippet 'package/snippets/resource_item.html', pkg=pkg, res=resource, url_is_edit=true, can_edit=can_edit %}
            {% endfor %}
        </ul>
    {% else %}
        {% trans url=h.url_for('resource.new', id=pkg.name) %}
        <p class="empty">This dataset has no data, <a href="{{ url }}">why not add some?</a></p>
    {% endtrans %}
    {% endif %}
{% endblock %}

{% block page_primary_action %}
    {% if h.check_access('resource_create', {'package_id':c.pkg_dict.id }) %}
        {% link_for _('Add new resource'), named_route='resource.new', id=c.pkg_dict.name, class_='btn btn-primary', icon='plus' %}
    {% endif %}

{% endblock %}

ckanext/spc/templates/package/search.html
{% ckan_extends %}

{% block header %}
    <div class="header-search-wrapper">
        {{ super() }}
    </div>
{% endblock %}

{% block primary_content %}
    <section class="module" onload="leafletMapAlt()">
        <div class="module-content">
            {% block page_primary_action %}
                <div class="page_primary_action">
                    {% if h.check_access('package_create') %}
                        {{ h.snippet ('snippets/add_dataset.html', dataset_type=dataset_type) }}
                    {% endif %}

                    {# just in case you'll ever want to download search results #}
                    {% if h.check_access('spc_bulk_download') and false %}
                        <button class="btn btn-primary"
                                data-module="spc-bulk-download"
                                data-module-query-string="{{ h.url_for('spc_package.list_ids') }}?{{ request.query_string.decode() }}" >
                            <i class=" fa fa-download"></i>
                            {{ _('Download files') }}
                        </button>
                    {% endif %}
                </div>
            {% endblock %}
            {% block form %}
                {% snippet 'ckanext-discovery/snippets/search_suggestions.html' %}
                {% set facets = {
                    'fields': c.fields_grouped,
                    'search': c.search_facets,
                    'titles': c.facet_titles,
                    'translated_fields': c.translated_fields,
                    'remove_field': c.remove_field }
                %}
                {% set sorting = [
                    (_('Relevance'), 'score desc, _five_star_rating desc, metadata_modified desc'),
                    (_('Open Data Rating'), '_five_star_rating desc, score desc, metadata_modified desc'),
                    (_('Name Ascending'), 'title_string asc'),
                    (_('Name Descending'), 'title_string desc'),
                    (_('Last Modified'), 'metadata_modified desc'),
                    (_('Popular'), 'views_recent desc') if g.tracking_enabled else (false, false) ]
                %}
                {% snippet 'snippets/search_form.html', form_id='dataset-search-form', type='dataset', query=c.q, sorting=sorting, sorting_selected=c.sort_by_selected, count=c.page.item_count, facets=facets, show_empty=request.params, error=c.query_error, fields=c.fields %}
            {% endblock %}
            {% block package_search_results_list %}
                {{ h.snippet('snippets/package_list.html', packages=c.page.items) }}
            {% endblock %}
        </div>

        {% block package_search_results_api %}
            <section class="module api-link">
                <div class="module-content">
                    {% block package_search_results_api_inner %}
                        <small>
                            {% set api_link = h.link_to(_('API'), h.url_for(controller='api', action='get_api', ver=3)) %}
                            {% set api_doc_link = h.link_to(_('API Docs'), 'http://docs.ckan.org/en/{0}/api/'.format(g.ckan_doc_version)) %}
                            {% if g.dumps_url -%}
                                {% set dump_link = h.link_to(_('full {format} dump').format(format=g.dumps_format), g.dumps_url) %}
                                {% trans %}
                                You can also access this registry using the {{ api_link }} (see {{ api_doc_link }}) or download a {{ dump_link }}.
              {% endtrans %}
                            {% else %}
              {% trans %}
              You can also access this registry using the {{ api_link }} (see {{ api_doc_link}}).
              {% endtrans %}
                            {%- endif %}
                        </small>
                    {% endblock %}
                </div>
            </section>
        {% endblock %}

    </section>

    {% block page_pagination %}
        {{ c.page.pager(q=c.q) }}
    {% endblock %}

{% endblock %}

{% block secondary_content %}
    {% snippet 'snippets/spc_facet_list.html', facet_titles=c.facet_titles %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {% if h.spc_hotjar_enabled() %}
        <!-- Hotjar Tracking Code for pacificdata.org -->
        <script>
         (function(h,o,t,j,a,r){
             h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
             h._hjSettings={hjid:1051527,hjsv:6};
             a=o.getElementsByTagName('head')[0];
             r=o.createElement('script');r.async=1;
             r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
             a.appendChild(r);
         })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
        </script>
  {% endif %}
{% endblock %}

ckanext/spc/templates/package/spc_download_tracking.html
{% extends 'package/read_base.html' %}

{% block primary_content_inner %}

    {% if pager %}
        <br/>
        <div class="report">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>{{ _('Resource') }}</th>
                        <th>{{ _('User') }}</th>
                        <th>{{ _('Date') }}</th>
                    </tr>
                </thead>
                {% for row in pager %}
                    <tr>
                        <td>
                            <a href="{{ h.url_for('resource.read', id=pkg_dict.id, resource_id=row.resource_id) }}">
                                {{ row.resource_name or _('Unnamed') }}
                            </a>
                        </td>
                        <td>
                            <a href="{{ h.url_for('user.read', id=row.user) }}">
                                {{ row.user }}
                            </a>
                        </td>
                        <td>
                            {{ h.render_datetime(h.date_str_to_datetime(row.downloaded_at), with_hours=True) }}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>

        {{ pager.pager() }}
    {% else %}
        <p class="empty">
            {{ _('There is no download records here yet.') }}
        </p>
    {% endif %}



{% endblock %}