ckanext/spc/views.py
# -*- coding: utf-8 -*-
import os
import logging
from datetime import datetime
from flask import Blueprint, send_file

import ckan.lib.jobs as jobs
import ckan.model as model
from ckan.common import _, g, request
from ckan.plugins import toolkit
import ckan.lib.helpers as h
import ckan.lib.plugins
import ckan.lib.base as base
import ckan.logic as logic

from ckanext.spc.jobs import broken_links_report
import ckanext.scheming.helpers as scheming_helpers
from ckanext.spc.model.search_query import SearchQuery


log = logging.getLogger(__name__)
render = base.render
abort = base.abort

PER_PAGE = 20


def switch_admin_state(id):
    if not toolkit.check_access('sysadmin', {'user': g.user}):
        return toolkit.abort(403, _('Not authorized'))

    user = model.User.get(id)
    if not user:
        return toolkit.abort(404, _('User does not exist'))
    if g.user == user.name:
        return toolkit.abort(403, _('Not authorized'))
    user.sysadmin = not user.sysadmin
    user.save()

    return toolkit.redirect_to('user.read', id=id)


def broken_links():
    QUEUE_NAME = 'default'
    queue = jobs.get_queue(QUEUE_NAME)
    queue._default_timeout = 3600 * 24
    try:
        toolkit.check_access('sysadmin', {'user': g.user, model: model})
    except toolkit.NotAuthorized:
        return toolkit.abort(403)
    filepath = toolkit.config['spc.report.broken_links_filepath']
    try:
        last_check = datetime.fromtimestamp(os.stat(filepath).st_mtime)
    except OSError:
        last_check = None
    active_jobs_count = jobs.get_queue(QUEUE_NAME).count
    if request.method == 'POST':
        action = request.form.get('action')
        if action == 'download' and last_check:
            return send_file(
                filepath,
                as_attachment=True,
                attachment_filename='SPC-BrokenLinks-{:%Y-%m-%d}.csv'.format(
                    last_check))

        elif action == 'start':
            jobs.enqueue(broken_links_report,
                         kwargs={'recepients': [g.user]},
                         queue=QUEUE_NAME)
            h.flash_notice('Report generation in progress. '
                           'You will recieve email notification '
                           'as soon as report finished')
            return h.redirect_to('spc_admin.broken_links')
    if active_jobs_count:
        h.flash_error('There are unfinished '
                      'report generation processes in progress. '
                      'You will not be able to manually start checker '
                      'until they are finished.')
    extra_vars = {
        'last_check': last_check,
        'active_jobs_count': active_jobs_count
    }
    return toolkit.render('admin/broken_links.html', extra_vars)



def index():
    context = {
        'model': model,
        'session': model.Session,
        'user': g.user,
        'auth_user_obj': g.userobj
    }
    # Package needs to have a organization group in the call to
    # check_access and also to save it
    try:
        logic.check_access('sysadmin', context, {})
    except logic.NotAuthorized:
        base.abort(403, _('Need to be system administrator'))

    if request.method == 'POST':
        query_name = request.POST['q_name']
        model.Session.query(SearchQuery).filter(SearchQuery.query == query_name).delete()
        model.Session.commit()
        h.flash_success(_('The query has been removed'))

    page = h.get_page_number(request.params)
    total = model.Session.query(SearchQuery).count()
    queries = model.Session.query(SearchQuery).order_by(
        SearchQuery.count.desc()
    ).limit(PER_PAGE).offset((page - 1) * PER_PAGE)
    pager = h.Page(
        collection=queries,
        page=page,
        url=lambda page: h.url_for('search_queries.index', page=page),
        item_count=total,
        items_per_page=PER_PAGE
    )

    return render(
        'search_queries/index.html', {
            'queries': queries,
            'pager': pager
        }
    )


spc_user = Blueprint('spc_user', __name__)
spc_admin = Blueprint('spc_admin', __name__)
spc_package = Blueprint('spc_package', __name__)
search_queries = Blueprint('search_queries', __name__)

spc_user.add_url_rule(u'/user/switch_admin_state/<id>',
                      view_func=switch_admin_state,
                      methods=(u'POST', ))

spc_admin.add_url_rule(u'/ckan-admin/broken-links',
                       view_func=broken_links,
                       methods=(u'GET', u'POST'))

search_queries.add_url_rule(
    "/ckan-admin/search-queries", view_func=index, methods=(u'GET', u'POST')
)

blueprints = [spc_user, spc_admin, spc_package, search_queries]

ckanext/spc/templates/user/edit.html
{% ckan_extends %}

{% block secondary_content %}
  <section class="module module-narrow module-shallow">
    <h2 class="module-heading"><i class="fa fa-info-circle"></i> {{ _('Account Info') }}</h2>
    <div class="module-content">
      {% trans %}
        <p>Your profile lets other CKAN users know about who you are and what you do.</p>
      {% endtrans %}
    </div>
  </section>
{% endblock %}

ckanext/spc/templates/user/login.html
{% ckan_extends %}

{% block primary_content %}
  <section class="module login">
    <div class="module-content">
      <h1 class="page-heading">{% block page_heading %}{{ _('Login') }}{% endblock %}</h1>
      {% block form %}
        {% snippet "user/snippets/login_form.html", action=g.login_handler, error_summary=error_summary %}
      {% endblock %}
    </div>
  </section>
{% endblock %}

ckanext/spc/templates/user/new.html
{% ckan_extends %}

{% block primary_content %}
  <article class="module register">
    <div class="module-content">
      {% block primary_content_inner %}
      <h1 class="page-heading">
        {% block page_heading %}{{ _('Register for an Account') }}{% endblock %}
      </h1>
      {{ form | safe }}
      {% endblock %}
    </div>
  </article>
{% endblock %}

ckanext/spc/templates/user/read_base.html
{% ckan_extends %}
{% block content_action %}
    {{ super() }}
    {% if h.check_access('sysadmin') and c.user != user.name%}
        <form action="{{ h.url_for('spc_user.switch_admin_state', id=user.id) }}" method="post" class="inline display-inline">
            <button class="btn btn-default">
                <i class="fa fa-user"></i>
                {{ _( ('Remove from' if user.sysadmin else 'Add to') ~ ' admins') }}
            </button>
        </form>
    {% endif %}
{% endblock %}